#!/bin/bash
read liczba if [[ $liczba -gt 0 ]] then
	echo "liczba jest dodatnia" elif [[ $liczba -lt 0 ]] then
	echo "liczba jest ujemna" else [[ $liczba -eq 0 ]]
	echo "Liczba jest rowna 0" fi exit 0; 
zad2
#!/bin/bash
read sciezka if [[ -f $sciezka ]] then
	echo "sciezka jest plikiem" elif [[ -d $sciezka ]] then
	echo "sciezka jest katalogiem" else
	echo "scieżka nie istnieje" fi exit 0;
zad3
#!/bin/bash
case $1 in 1)
 echo "styczen"
 ;; 2) echo "luty"
 ;; 3) echo "marzec"
 ;; 4) echo "kwiecien"
 ;; 5) echo "maj"
 ;; 6) echo "czerwiec"
 ;; 7) echo "lipiec"
 ;; 8) echo "sierpien"
 ;; 9) echo "wrzesien"
 ;; 10) echo "pazdziernik"
 ;; 11) echo "listopad"
 ;; 12) echo "grudzien"
 ;; *)
  esac
exit 0;
zad4
#!/bin/bash
read napis for ((i = $1; i>0 ; i=i-1 )) do
 echo $napis done
exit 0;
zad5
#!/bin/bash
read liczba suma=0 until [ $liczba -eq 0 ] do
 suma=$[$suma+$liczba]
 read liczba done echo $suma
exit 0;
zad6
#!/bin/bash
cd ~/ du > 
/home/LABPK/azyskowski/Pulpit/srodowisko_programisty/lab6/pliki.dat
exit 0;
zad7
#!/bin/bash

if [[ $1 == *.txt ]]
then
nano $1
fi
if [[ $1 == *.sh ]]
then
./$1 fi
zad8
#!/bin/bash

select x in "dodawanie" "odejmowanie" "mnozenie" "dzielenie" "wyjscie"
do

case $x in
"dodawanie")
 echo $(($1+$2));;
"odejmowanie")
 echo $(($1-$2));;
"mnozenie")
 echo $(($1*$2));;
"dzielenie") 
 echo $(($1/$2));;	
"wyjscie") 
exit 0;;
 esac

done
exit 0
